name: github_sign_in
description: Sign In With GitHub
version: 0.0.2
author: Long Do <me@dotronglong.com>
homepage: https://github.com/dotronglong/dart-github-sign-in

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  flutter_webview_plugin: ^0.3.8
